apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::399804333105:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5Z63PGQU4NIP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::399804333105:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-13T06:59:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1488"
  uid: ec273082-d755-44fd-8ac4-4326f8b534f4
